version: "3.8"

services:
  app:
    container_name: admin-prod
    image: admin-prod
    build:
      context: .
      target: production
    volumes:
      - './src:/app/src'
    ports:
      - 3002:3002